### PR TITLE
Unique issues

### PR DESCRIPTION
**Pull request by jasonconnery**
The same issue can be repeated multiple times in the slack message. Testing if distinctBy will fix this.

### CODE REVIEW

**Review by otormaigh — CHANGES_REQUESTED** [review]

**Comment by jasonconnery** [comment]
Screenshot 2023-05-03 at 15 16 24
Getting an error initialising the plugin during install

**Comment by otormaigh** [comment]
> `org.springframework.beans.BeanInstantiationException:`

We don't explicitly use Spring in the project, but I'd guess its being used internally in one of the TeamCity dependencies. You could try rolling them back to `2019.1.3`.

Was there something specific in that latest version TeamCity that you needed?

**Comment by jasonconnery** [comment]
> > `org.springframework.beans.BeanInstantiationException:`
> 
> We don't explicitly use Spring in the project, but I'd guess its being used internally in one of the TeamCity dependencies. You could try rolling them back to `2019.1.3`.
> 
> Was there something specific in that latest version TeamCity that you needed?

Not really, I was just keeping it in sync with the version of Teamcity we have installed , which is 2022.10

**Comment by jasonconnery** [comment]
Closing this one cos of all the additional stuff re-kotlin we haven't tested / get working yet. I've a new PR for a simpler approach.

**Pull request closed without merging**
